[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
target-version = "py312"
line-length = 100
fix = true

[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM"]
fix = true

[tool.ruff.lint.isort]
known-first-party = ["app", "opsbox", "tests"]
combine-as-imports = true
