architecture: standalone

auth:
  enabled: false   # dev only; turn on in prod/staging

master:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

replica:
  replicaCount: 0

metrics:
  enabled: true
  serviceMonitor:
    enabled: false
